before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/postmanctl/main.go
  goos:
    - linux
    - windows
    - darwin
  ldflags:
    - -s -w -X "github.com/kevinswiber/postmanctl/internal/runtime/cmd.version=v{{.Version}}"
    - -X "github.com/kevinswiber/postmanctl/internal/runtime/cmd.commit={{.ShortCommit}}"
    - -X "github.com/kevinswiber/postmanctl/internal/runtime/cmd.date={{.Date}}" 
brews:
  - name: postmanctl
    custom_block: |
      head do
        url "https://github.com/kevinswiber/postmanctl.git"
        depends_on "go"
      end
    install: |
      if head?
        system "go", "build", "./cmd/postmanctl"
      end

      bin.install "postmanctl"
    github:
      owner: kevinswiber
      name: homebrew-postmanctl
    commit_author:
      name: Kevin Swiber
      email: kswiber@gmail.com
    folder: Formula
    homepage: https://github.com/kevinswiber/postmanctl
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
