before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/postmanctl/main.go
  goos:
    - linux
    - windows
    - darwin
brews:
  - name: postmanctl
    github:
      owner: kevinswiber
      name: homebrew-postmanctl
    commit_author:
      name: Kevin Swiber
      email: kswiber@gmail.com
    folder: Formula
    homepage: https://github.com/kevinswiber/postmanctl
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
